### ISSUE TITLE
Mob hunter 2 quest resets other quests

### ISSUE THREAD

**Issue by billyty08** [Inverseder/Cortex-modpack#1]
When you claim the rewards from this quest it blacks out all the quests in line after it. If you complete Mob Hunter 2 again the others will still be completed and back to normal unless you claim the rewards from mob hunter 2 again. If this is supposed to be a repeatable quest I would suggest placing it at the end of a line like mob hunter  1

**Comment by Inverseder** [comment]
Thanks for you reply, i will post a patch today to fix it.
