### ISSUE TITLE
craft wood hammer

### ISSUE THREAD

**Issue by hades60** [Inverseder/Cortex-modpack#4]
the craft of the wooden hammer is not valid it gives the wooden wrench

**Comment by Inverseder** [comment]
You can used this arrow to switch with the craft of wood hammer and wood wrench.
![Capture](https://user-images.githubusercontent.com/46263382/54336109-808dae00-4644-11e9-8970-f324ed0d939c.PNG)

**Comment by hades60** [comment]
oh really thank you i not look that
