### ISSUE TITLE
Mekanism quests not detecting

### ISSUE THREAD

**Issue by billyty08** [Inverseder/Cortex-modpack#6]
There are a few quests-namely the compresser and combiner ones and another I can't remember that don't complete when you craft but will as soon as I cheated them in. I believe there is a meta tag difference on the one crafted versus the one straight from cheating it in according to /ct hand testing

**Comment by billyty08** [comment]
Just happened with digital miner as well

**Comment by Inverseder** [comment]
Thanks for your reply I will post a new patch to fix mekanism quest tomorrow.
