### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by CircaShoes** [Inverseder/Cortex-modpack#7]
Hi,

The Game ist freezing when crafttweaker loads, could you fix this pls.

**Comment by Inverseder** [comment]
It's freezing when you load your game or if you load your world?

**Comment by CircaShoes** [comment]
its freezing when load up the game

**Comment by Inverseder** [comment]
And you can't continue to load?

**Comment by CircaShoes** [comment]
no i wait now about 2 hours, and it doesnt load

**Comment by Inverseder** [comment]
And how much ram you have allowed for Minecraft?

**Comment by CircaShoes** [comment]
9gb ram i tried with 12gb and it also did not work

**Comment by Inverseder** [comment]
Can you send me your latest log pls? I will try to find the problem.

**Comment by CircaShoes** [comment]
Okay, will do, but tomorrow.

**Comment by Inverseder** [comment]
Ok no problem

**Comment by CircaShoes** [comment]
i have delete everything, and make a fresh start and now it works

**Comment by Inverseder** [comment]
oh ok
