### ISSUE TITLE
Interacting with Wandering Wizard crashes the game on Cortex 4

### ISSUE THREAD

**Issue by kuh-lip-soh** [Inverseder/Cortex-modpack#8]
How to reproduce :
Spawning the Wandering Wizard from Mana and Artifice as normal, and then right click on him

Crash Report :
[crash-2024-03-23_13.39.19-client.txt](https://github.com/Inverseder/Cortex-modpack/files/14731568/crash-2024-03-23_13.39.19-client.txt)

**Comment by Inverseder** [comment]
Don't use optifine
